# Generated by Django 3.1.7 on 2021-03-24 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_url', models.CharField(blank=True, max_length=5)),
                ('url', models.URLField(max_length=255)),
                ('clicks', models.IntegerField(default=0)),
            ],
        ),
    ]
